# Generated by Django 4.2 on 2023-05-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_rename_category_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifmodel',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
