# Generated by Django 4.2 on 2023-04-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_animal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
    ]
